# Book settings
title: Urban Grammar AI | WP2 - Spatial Signatures
author: Dani Arribas-Bel, Martin Fleischmann
logo: logo.svg

execute:
  execute_notebooks: "off"
repository:
  url: https://github.com/urbangrammarai/spatial_signatures
launch_buttons:
  binderhub_url: https://mybinder.org
html:
  use_repository_button: true
