name: Build Jupyter book
on:
  push:
    branches:
      - master
jobs:
  build-html-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          miniconda-version: "latest"
          python-version: 3.7
          environment-file: environment.yml
          activate-environment: book

      - name: Build Jupyter book
        shell: bash -l {0}
        run: |
          make build-book

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs
          git commit -m "Build Jupyter book" -a --allow-empty

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
